spring.application.name=demo
spring.main.banner-mode=off

# Logging
logging.level.root=INFO
logging.level.org.springframework.security=DEBUG

# Thymeleaf
spring.thymeleaf.enabled=true

# === ONLY disable DB if NO_DATABASE=true ===
spring.autoconfigure.exclude=${NO_DATABASE:}

# Render port
server.port=${PORT:8080}